#!/usr/bin/env php
<?php declare(strict_types=1);

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('BADGER_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('BADGER_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require BADGER_COMPOSER_INSTALL;

use Symfony\Component\Console\Application;
use Badger\Commands\CoverageBadge;

$application = new Application();

$application->add(new CoverageBadge());

$application->run();
